import './globals.css'
import type { Metadata } from 'next' // metaデータ定義してそう
import { Inter } from 'next/font/google' // fontインストール？

const inter = Inter({ subsets: ['latin'] }) // ここわからん

export const metadata: Metadata = { // この書き方初めてみた　meta hoge~~のほげ部分定義してそう
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: { // ここの書き方わからんなぁ
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
